### PR TITLE
Upload latest image to dockerhub with each commit

### PR DESCRIPTION
**Pull request by kokosing**
Upload latest image to dockerhub with each commit

### CODE REVIEW

**Comment by losipiuk** [comment]
Is the new (numbered) version also created. Or only `latest` tag is changed?

**Comment by losipiuk** [comment]
Btw. This PR failed with following output:
```
The command "make" exited with 0.
$ if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; make latest; fi
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by kokosing** [comment]
Plan was to upload only latest. I do know why it failed. I thought I set
all the things  ; /

**Comment by losipiuk** [comment]
> Plan was to upload only latest

Hmm - I do not think it is common approach. What I saw that latest was just a pointer to a named container version.

**Comment by ArturGajowy** [comment]
I'd not do that - this means 'latest' becomes a snapshot. The convention is to have latest = max 'proper' version. If anything, I'd publish each commit under latest-snapshot :)

**Pull request closed without merging**
